version: "3"
services:
  django:
    container_name: django_hospital_app
    build: .
    ports:
      - "8000:8000"
    image: django_hospital:v1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./static:/app/static
  postgres:
    container_name: django_hospital_postgres
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local
