# Generated by Django 5.0 on 2023-12-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
