# Generated by Django 5.0 on 2023-12-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_workinghour_break_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
