# Generated by Django 5.0 on 2023-12-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialty_doctor_specialties_workinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
