# Generated by Django 5.0 on 2023-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_workinghour_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='non_reimbursements',
            field=models.ManyToManyField(to='doctors.nonreimbursement'),
        ),
    ]
